### ISSUE TITLE
Angel City auto-titan entering obstructed/pilot-only area

### ISSUE THREAD

**Issue by GeckoEidechse** [R2Northstar/NorthstarNavs#2]
Image of location in question

![image](https://github.com/R2Northstar/NorthstarNavs/assets/40122905/23619e8e-c27d-4d51-9925-f18a8298819e)

**Comment by GeckoEidechse** [comment]
@Zanieon do you know if this has been fixed? ^^

**Comment by Zanieon** [comment]
Yeah this was one of the first issues i ran into when i did my navmeshes, but after 2 iterations i managed to fix, so Titan navs werent being generated in that hallway anymore.

**Comment by GeckoEidechse** [comment]
Awesome, closing as completed then :D
